In [1]:
# test for interpolation operation in pytorch
import torch

In [3]:
x = torch.empty(5,3)

In [4]:
x

tensor([[1.8040e+28, 1.8750e-19, 7.3909e+22],
        [2.4176e-12, 2.6209e+20, 4.1641e+12],
        [8.9625e-01, 7.9309e+34, 7.9439e+08],
        [3.2604e-12, 7.3113e+34, 9.5492e-01],
        [7.3154e+34, 5.9682e-02, 7.0374e+22]])

In [5]:
x = torch.rand(5,3)

In [7]:
x

tensor([[0.0185, 0.5577, 0.0886],
        [0.0738, 0.8659, 0.4649],
        [0.7631, 0.7022, 0.1453],
        [0.5478, 0.8140, 0.8283],
        [0.3238, 0.0589, 0.0143]])

In [10]:
x = torch.zeros(5,3)

In [11]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x = torch.tensor([10,20])

In [13]:
x

tensor([10, 20])

In [16]:
x = x.new_ones(5, 3, dtype=torch.double)

In [18]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
x = torch.randn_like(x,dtype=torch.float)

In [20]:
x

tensor([[-1.7032,  0.9200,  1.4416],
        [ 2.7125,  0.1146,  0.8252],
        [ 2.4347, -0.5704,  0.6789],
        [-0.2898, -0.4500,  1.0378],
        [ 0.2426, -0.8294,  0.2089]])

In [21]:
x.size()

torch.Size([5, 3])

In [22]:
x.shape

torch.Size([5, 3])

In [23]:
y = torch.rand(5,3)

In [24]:
y

tensor([[0.2749, 0.5117, 0.8395],
        [0.2343, 0.8845, 0.3179],
        [0.2403, 0.9132, 0.5497],
        [0.3551, 0.3716, 0.9086],
        [0.7402, 0.1041, 0.2176]])

In [25]:
print(x+y)

tensor([[-1.4283,  1.4317,  2.2810],
        [ 2.9468,  0.9991,  1.1431],
        [ 2.6750,  0.3428,  1.2286],
        [ 0.0653, -0.0784,  1.9464],
        [ 0.9828, -0.7254,  0.4265]])


In [26]:
torch.add(x,y)

tensor([[-1.4283,  1.4317,  2.2810],
        [ 2.9468,  0.9991,  1.1431],
        [ 2.6750,  0.3428,  1.2286],
        [ 0.0653, -0.0784,  1.9464],
        [ 0.9828, -0.7254,  0.4265]])

In [27]:
x

tensor([[-1.7032,  0.9200,  1.4416],
        [ 2.7125,  0.1146,  0.8252],
        [ 2.4347, -0.5704,  0.6789],
        [-0.2898, -0.4500,  1.0378],
        [ 0.2426, -0.8294,  0.2089]])

In [29]:
x[1,:]

tensor([2.7125, 0.1146, 0.8252])

In [30]:
x = torch.randn(4,4)

In [31]:
x

tensor([[-0.8819,  0.2923, -0.7376,  1.3239],
        [-0.6473, -1.4775,  0.8876, -0.6672],
        [ 0.0090, -1.5301, -0.3274,  1.5795],
        [ 0.0807, -0.5971, -0.9020,  0.4641]])

In [32]:
x.view(16)

tensor([-0.8819,  0.2923, -0.7376,  1.3239, -0.6473, -1.4775,  0.8876, -0.6672,
         0.0090, -1.5301, -0.3274,  1.5795,  0.0807, -0.5971, -0.9020,  0.4641])

In [33]:
x.view(-1,8)

tensor([[-0.8819,  0.2923, -0.7376,  1.3239, -0.6473, -1.4775,  0.8876, -0.6672],
        [ 0.0090, -1.5301, -0.3274,  1.5795,  0.0807, -0.5971, -0.9020,  0.4641]])

In [34]:
x = torch.randn(1)

In [35]:
x

tensor([0.2914])

In [36]:
x.item()

0.2913835048675537

In [45]:
a =  torch.ones(5)

In [46]:
a

tensor([1., 1., 1., 1., 1.])

In [47]:
b = a.numpy()

In [48]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [49]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [50]:
a

tensor([2., 2., 2., 2., 2.])

In [51]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [52]:
torch.cuda.is_available()

True

In [53]:
device = torch.device("cuda")

In [54]:
x

tensor([0.2914])

In [55]:
y = torch.ones_like(x, device=device)

In [56]:
y

tensor([1.], device='cuda:0')

In [57]:
x = x.to(device)

In [58]:
x

tensor([0.2914], device='cuda:0')

In [59]:
z = x + y

In [60]:
z

tensor([1.2914], device='cuda:0')

In [61]:
x

tensor([0.2914], device='cuda:0')

In [62]:
x = torch.ones(2,2,requires_grad=True)

In [63]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [64]:
y = x + 2

In [65]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [66]:
y.grad_fn

In [67]:
y.grad

In [68]:
z = y * y * 3

In [69]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [70]:
out = z.mean()

In [71]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [72]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [73]:
out.backward()

In [74]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [76]:
z.grad

In [77]:
y.grad

In [78]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [79]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [82]:
x = torch.randn(3,requires_grad=True)

In [83]:
x

tensor([0.3880, 0.7609, 0.1168], requires_grad=True)

In [84]:
y = x * 2

In [85]:
y

tensor([0.7760, 1.5218, 0.2336], grad_fn=<MulBackward0>)

In [86]:
y.data.norm()

tensor(1.7241)

In [87]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [89]:
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [91]:
list(net.parameters())

[Parameter containing:
 tensor([[[[ 0.3032, -0.2588, -0.0679],
           [ 0.3279,  0.3211, -0.3104],
           [-0.1591, -0.3198,  0.1643]]],
 
 
         [[[ 0.3252, -0.2489, -0.0747],
           [ 0.2289, -0.3259,  0.0686],
           [ 0.0063,  0.0769,  0.2556]]],
 
 
         [[[ 0.2675, -0.0402,  0.0319],
           [-0.2850, -0.0154, -0.2041],
           [-0.1469, -0.2335, -0.1959]]],
 
 
         [[[-0.3294,  0.2993,  0.0469],
           [-0.1754, -0.0092, -0.1267],
           [ 0.0845,  0.2608, -0.0682]]],
 
 
         [[[-0.2289,  0.2601,  0.1150],
           [ 0.2553, -0.2908,  0.3213],
           [ 0.0500, -0.0584, -0.0482]]],
 
 
         [[[-0.1756, -0.1578,  0.3188],
           [ 0.0038, -0.1281, -0.2067],
           [ 0.2529, -0.1156,  0.0431]]]], requires_grad=True),
 Parameter containing:
 tensor([-0.1644, -0.1019,  0.1811,  0.0277,  0.2572,  0.2445],
        requires_grad=True),
 Parameter containing:
 tensor([[[[ 9.3549e-03, -3.3289e-02, -8.0891e-02],
           [

In [92]:
input = torch.randn(1,1,32,32)

In [93]:
out = net(input)

In [94]:
out

tensor([[-0.0594, -0.0504, -0.0825, -0.0581, -0.0539,  0.0385, -0.0978, -0.1197,
         -0.1653, -0.0781]], grad_fn=<AddmmBackward>)

In [95]:
net.zero_grad()

In [96]:
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [98]:
out.backward(torch.randn(1,10))